name: FinForce
favicon: null
layout_spectrum: 0.5101205171085894
typography_spectrum: 0.2272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c1020'
    - '#2b3f70'
    - '#9a9ca2'
    - '#c2c4c8'
  brandStrength: 1
  lightness: 0.8724544777069241
  saturation: 0.8125
  rhythmicContrast: 0.27095267409458756
purpose: []
