name: FinForce
favicon: null
layout_spectrum: 0.5101205171085894
typography_spectrum: 0.4011121822986752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5848456721287221
  lightness: 0.8724544777069241
  saturation: 0.4744852054864168
  rhythmicContrast: 0.27095267409458756
purpose: []
